### ISSUE TITLE
Remove unused property

### ISSUE THREAD

**Issue by zmraul** [canonical/charmed-kafka-snap#47]
When the snap starts, the following warning shows:
```
charmed-kafka.daemon[16803]: log4j:WARN No such property [datePattern] in org.apache.log4j.RollingFileAppender.
```
#### Solution

Remove `log4j.appender.<appenderName>.DatePattern='.'yyyy-MM-dd-HH` lines

**Comment by imanenami** [comment]
Hi @zmraul @marcoppenheimer 

Could you kindly assign this to me. Thanks!
